#!/usr/bin/env node

var program = require('commander');

program
  .version('1.0.0')
  .command('install [name]', 'install one or more packages').alias('i')
  .command('list', 'list packages installed')
  .parse(process.argv);
