#!/usr/bin/env node

const fs = require('fs');
const request = require('request');
const fe = require('./lib/fe');
const readPackageJSON = require('./lib/read-package-json');
const checkPackageJSON = require('./lib/check-for-package');

var program = require('commander');

program
  .option('-f, --force', 'force installation')
  .parse(process.argv);

var pkgs = program.args;

if (!pkgs.length) {
  var result = checkPackageJSON();
  if (result===true) {
    //install the packages
  } else {
    console.log(result);
    process.exit(1);
  }
}

console.log();
if (program.force) console.log('  force: install');

pkgs.forEach(function(pkg) {
  opts = {
    pkg: pkg,
    version: "0.0.1"
  }
  fe(opts);
})
console.log();
